import type {
  AnalyzerService,
  AnalysisResult,
  FantasyPlayer,
  FantasyTeam,
  FantasyConfig,
} from "../types/player.ts";
import {StatsScraperService} from "./statsScraper.ts";
import {
  mathOptimizer,
  resolveWeights,
  type MathLineup,
  type OptimizerWeightOverrides,
  type ScoreWeights,
  type WeightKey,
} from "../services/mathOptimizer.ts";
import {contestSimulator, DEFAULT_SIM_CONFIG, type SimmedLineup} from "./contestSimulator.ts";
import {
  selectPortfolio,
  toPlayers,
  modeRecommendation,
  DEFAULT_PORTFOLIO,
} from "./portfolio.ts";
import {createProgressBar, printScoringDiagnostics} from "../cli/output.ts";
import {env} from "../env.ts";

/** How many perturbed-optimal field runs model other sharp drafters. */
const FIELD_PERTURB_RUNS = 14;
const FIELD_PERTURB_LINEUPS = 12;

function randomPerturbation(base: ScoreWeights): OptimizerWeightOverrides {
  const out = {} as ScoreWeights;
  for (const key of Object.keys(base) as WeightKey[]) {
    const factor = key.startsWith("hist_") || key === "cardRatingBenefit"
      ? 0.5 + Math.random() * 1.1
      : 0.6 + Math.random() * 0.9;
    out[key] = Math.max(0, Number((base[key]! * factor).toFixed(4)));
  }
  return out;
}

/**
 * Builds the modeled competitor pool: diverse strong lineups generated by
 * re-running the optimizer under random weight jitter (each run ≈ one sharp
 * drafter's personal model), deduped by roster signature.
 */
function generateSharpFieldLineups(
  players: FantasyPlayer[],
  teams: FantasyTeam[],
  config: FantasyConfig,
): MathLineup[] {
  const seen = new Set<string>();
  const pool: MathLineup[] = [];
  for (let k = 0; k < FIELD_PERTURB_RUNS; k++) {
    const overrides = randomPerturbation(resolveWeights());
    const lineups = mathOptimizer.optimizeIsolated(
      players,
      teams,
      {...config, lineupLimit: FIELD_PERTURB_LINEUPS},
      overrides,
    );
    for (const lineup of lineups) {
      const sig = [...lineup.players]
        .map((p) => p.id)
        .sort()
        .join("|");
      if (!seen.has(sig)) {
        seen.add(sig);
        pool.push(lineup);
      }
    }
  }
  // Restore base scoring state so downstream μ/σ use untampered weights.
  mathOptimizer.applyWeights();
  return pool;
}

export class FantasyAnalyzerService implements AnalyzerService {
  async analyze(
    players: FantasyPlayer[],
    teams: FantasyTeam[],
    config: FantasyConfig,
    sourceUrl: string,
  ): Promise<AnalysisResult> {
    const mode = config.mode ?? "consistency";

    const statsBar = createProgressBar("Stage 1 · Enriching player stats");
    statsBar.tick(0, 1, "Fetching historical HLTV stats (cache or disk)...");
    const scraper = new StatsScraperService();
    const enrichedPlayers =
      await scraper.enrichPlayersWithHistoricalStats(players);
    statsBar.done("Stats enriched", 1);

    const mathBar = createProgressBar("Stage 2 · Generating optimal lineups");
    mathBar.tick(0, 1, "Crunching combinations...");
    const bestLineups = mathOptimizer.optimize(enrichedPlayers, teams, config);

    if (bestLineups.length === 0) {
      throw new Error(
        "Could not find any mathematically valid lineups for given budget and constraints.",
      );
    }
    mathBar.done(`Generated ${bestLineups.length} valid lineups`, 1);

    // ── Stage 3: contest simulation ─────────────────────────────────
    let ranked: SimmedLineup[];
    if (mode === "ev") {
      ranked = bestLineups.map((lineup) => ({
        lineup,
        objective: lineup.expectedBaseScore,
        meanSimScore: lineup.expectedBaseScore,
        metrics: {
          pTop50: 0,
          pTop30: 0,
          pTop10: 0,
          pTop05: 0,
          meanPercentile: 0,
        },
      }));
    } else {
      const simBar = createProgressBar(
        `Stage 3 · Simulating contest (${DEFAULT_SIM_CONFIG.iterations.toLocaleString()} iterations)`,
      );
      simBar.tick(0, 1, "Modeling sharp field (perturbed optimizer runs)...");
      const sharpField = generateSharpFieldLineups(enrichedPlayers, teams, config);
      simBar.tick(1, 1, `Drawing performances vs ${sharpField.length}+ strong field lineups...`);
      ranked = contestSimulator.simulate(
        bestLineups,
        enrichedPlayers,
        teams,
        mathOptimizer,
        mode,
        DEFAULT_SIM_CONFIG,
        sharpField,
      );
      simBar.done(
        `Ranked ${ranked.length} candidates vs modeled field`,
        1,
      );
    }

    if (env.SCORING_DIAGNOSTICS) {
      printScoringDiagnostics(mathOptimizer.getLatestDiagnostics());
    }

    const playerScores = new Map<
      string,
      {id: string; name: string; team: string; rating: number}
    >();
    for (const p of enrichedPlayers) {
      playerScores.set(p.id, {
        id: p.id,
        name: p.name,
        team: p.team,
        rating: mathOptimizer.getExpectedBaseScore(p),
      });
    }
    const top20ByRating = Array.from(playerScores.values())
      .sort((a, b) => b.rating - a.rating)
      .slice(0, 30);

    const portfolio = selectPortfolio(ranked, DEFAULT_PORTFOLIO);
    const {recommendedIndex, text: recommendation} = modeRecommendation(
      mode,
      portfolio,
    );

    const toEntry = (
      simmed: SimmedLineup,
      idx: number,
    ) => {
      const playersOut = toPlayers(simmed);
      return {
        players: playersOut,
        lineupIndex: idx,
        score:
          mode === "ev"
            ? simmed.lineup.expectedBaseScore
            : simmed.objective * 100,
        totalPrice: simmed.lineup.totalPrice,
        consistency:
          mode === "ev"
            ? undefined
            : {
                pTop50: simmed.metrics.pTop50,
                pTop30: simmed.metrics.pTop30,
                pTop10: simmed.metrics.pTop10,
                meanPercentile: simmed.metrics.meanPercentile,
                medianRank: 0,
              },
      };
    };

    const allEntries = ranked.slice(0, Math.max(50, config.lineupLimit ?? 50)).map(
      (simmed, idx) => toEntry(simmed, idx),
    );
    const portfolioEntries = portfolio.map((p) =>
      toEntry(p.entry, p.rank - 1),
    );

    const bestSimmed = ranked[0]!;
    const finalPlayers = toPlayers(bestSimmed);

    return {
      players: finalPlayers,
      analyzedAt: new Date(),
      sourceUrl,
      reasoning: `${mode} objective over ${DEFAULT_SIM_CONFIG.iterations.toLocaleString()}-iteration contest simulation`,
      mode,
      recommendedLineupIndex: recommendedIndex,
      recommendation,
      top3: portfolioEntries.slice(0, 3).map((entry) => ({
        players: entry.players,
        lineupIndex: entry.lineupIndex,
        reasoning: `Portfolio pick #${entry.lineupIndex + 1}`,
        score: entry.score,
      })),
      portfolio: portfolioEntries,
      allScoredLineups: allEntries,
      top20ByRating,
    };
  }
}
