import {z} from "zod";

const envSchema = z.object({
  BLACKLISTED_PLAYERS: z
    .string()
    .default("")
    .transform((val) =>
      val
        .split(",")
        .map((s) => s.trim())
        .filter((s) => s.length > 0),
    ),
  SCORING_DIAGNOSTICS: z
    .string()
    .optional()
    .transform((val) => val === "true"),
  WEIGHT_CARD_RATING_BENEFIT: z.coerce.number().optional(),
  WEIGHT_HISTORICAL_TOP10_RATING_BENEFIT: z.coerce.number().optional(),
  WEIGHT_HISTORICAL_TOP20_RATING_BENEFIT: z.coerce.number().optional(),
  WEIGHT_HISTORICAL_TOP30_RATING_BENEFIT: z.coerce.number().optional(),
  WEIGHT_HISTORICAL_TOP50_RATING_BENEFIT: z.coerce.number().optional(),
  WEIGHT_TOP_TEAM_RANK_BENEFIT: z.coerce.number().optional(),
  WEIGHT_AWPER_ROLE_BENEFIT: z.coerce.number().optional(),
  WEIGHT_LOW_DEATH_RATE_BENEFIT: z.coerce.number().optional(),
  WEIGHT_CT_VS_T_RATING_IMBALANCE_PENALTY: z.coerce.number().optional(),
  WEIGHT_STACK_CORRELATION_BENEFIT: z.coerce.number().optional(),
  WEIGHT_TOP_RANKED_TEAM_STACK_BENEFIT: z.coerce.number().optional(),
  WEIGHT_AWP_PER_ROUND_WEIGHT: z.coerce.number().optional(),
  WEIGHT_DEATH_PENALTY_WEIGHT: z.coerce.number().optional(),
  WEIGHT_PRICE_EFFICIENCY_BENEFIT: z.coerce.number().optional(),
  THRESHOLD_AWPER_ROLE_MIN_AWP_PER_ROUND: z.coerce.number().optional(),
  THRESHOLD_LOW_DEATH_RATE_MAX_DEATHS_PER_ROUND: z.coerce.number().optional(),
});

export const env = envSchema.parse({
  BLACKLISTED_PLAYERS: process.env.BLACKLISTED_PLAYERS,
  SCORING_DIAGNOSTICS: process.env.SCORING_DIAGNOSTICS,
  WEIGHT_CARD_RATING_BENEFIT: process.env.WEIGHT_CARD_RATING_BENEFIT,
  WEIGHT_HISTORICAL_TOP10_RATING_BENEFIT:
    process.env.WEIGHT_HISTORICAL_TOP10_RATING_BENEFIT,
  WEIGHT_HISTORICAL_TOP20_RATING_BENEFIT:
    process.env.WEIGHT_HISTORICAL_TOP20_RATING_BENEFIT,
  WEIGHT_HISTORICAL_TOP30_RATING_BENEFIT:
    process.env.WEIGHT_HISTORICAL_TOP30_RATING_BENEFIT,
  WEIGHT_HISTORICAL_TOP50_RATING_BENEFIT:
    process.env.WEIGHT_HISTORICAL_TOP50_RATING_BENEFIT,
  WEIGHT_TOP_TEAM_RANK_BENEFIT: process.env.WEIGHT_TOP_TEAM_RANK_BENEFIT,
  WEIGHT_AWPER_ROLE_BENEFIT: process.env.WEIGHT_AWPER_ROLE_BENEFIT,
  WEIGHT_LOW_DEATH_RATE_BENEFIT: process.env.WEIGHT_LOW_DEATH_RATE_BENEFIT,
  WEIGHT_CT_VS_T_RATING_IMBALANCE_PENALTY:
    process.env.WEIGHT_CT_VS_T_RATING_IMBALANCE_PENALTY,
  WEIGHT_STACK_CORRELATION_BENEFIT:
    process.env.WEIGHT_STACK_CORRELATION_BENEFIT,
  WEIGHT_TOP_RANKED_TEAM_STACK_BENEFIT:
    process.env.WEIGHT_TOP_RANKED_TEAM_STACK_BENEFIT,
  WEIGHT_AWP_PER_ROUND_WEIGHT: process.env.WEIGHT_AWP_PER_ROUND_WEIGHT,
  WEIGHT_DEATH_PENALTY_WEIGHT: process.env.WEIGHT_DEATH_PENALTY_WEIGHT,
  WEIGHT_PRICE_EFFICIENCY_BENEFIT:
    process.env.WEIGHT_PRICE_EFFICIENCY_BENEFIT,
  THRESHOLD_AWPER_ROLE_MIN_AWP_PER_ROUND:
    process.env.THRESHOLD_AWPER_ROLE_MIN_AWP_PER_ROUND,
  THRESHOLD_LOW_DEATH_RATE_MAX_DEATHS_PER_ROUND:
    process.env.THRESHOLD_LOW_DEATH_RATE_MAX_DEATHS_PER_ROUND,
});
